name: publish-npm
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checking out project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: install
        run: npm ci --ignore-scripts
      - name: 'Run test'
        run: npm run test
      - name: 'Bump the version'
        run: npm version ${{inputs.version}}
      - name: 'Publish the packages'
        run: npm publish
      - name: install
        run: npm ci --ignore-scripts
      - name: 'Run test'
        run: npm run test
      - name: 'Bump the version'
        run: npm version ${{inputs.version}}
      - name: 'Publish the packages'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Get new version
        id: new-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/ui
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: version ${{ steps.new-version.outputs.current-version}}
          commit_user_name: timbryandev-bot
          commit_user_email: ghbot@timbryan.dev
          tagging_message: 'v${{ steps.new-version.outputs.current-version }}'
          push_options: '--force'
